import {
  buildSkillSyncFiles,
  providerLabel,
  type SkillSyncFile,
  type SkillSyncManifest,
  type SkillSyncProvider,
} from "../../../src/lib/skillsSync.ts";

export interface GithubPublishConfig {
  fetchImpl: typeof fetch;
  token: string;
  repo: string;
  baseBranch: string;
  branchName: string;
  files: SkillSyncFile[];
  providers: SkillSyncProvider[];
  manifest: SkillSyncManifest;
}

export interface GithubPublishResult {
  branch: string;
  prUrl: string;
  filesPublished: number;
  commitSha: string;
}

export interface KimiUploadConfig {
  fetchImpl: typeof fetch;
  apiKey: string;
  files: SkillSyncFile[];
}

export interface KimiUploadResult {
  uploaded: number;
  files: Array<{
    file_id: string;
    filename: string;
    path: string;
  }>;
}

export function buildSkillSyncBranchName(now = new Date()): string {
  const pad = (value: number) => String(value).padStart(2, "0");
  const stamp = [
    now.getUTCFullYear(),
    pad(now.getUTCMonth() + 1),
    pad(now.getUTCDate()),
  ].join("") + "-" + [pad(now.getUTCHours()), pad(now.getUTCMinutes()), pad(now.getUTCSeconds())].join("");

  return `sync/skills/${stamp}`;
}

export function createGithubPrBody(manifest: SkillSyncManifest, providers: SkillSyncProvider[]): string {
  return [
    "## Skills sync generated by Alexandria",
    "",
    `- Scope: \`${manifest.scope}\``,
    `- Skills exportadas: **${manifest.total_skills}**`,
    `- Providers: ${providers.map((provider) => `\`${providerLabel(provider)}\``).join(", ")}`,
    `- Gerado em: ${manifest.generated_at}`,
    "",
    "Atualiza apenas o diretório `exports/` com os artefatos de sincronização para Claude Web, ChatGPT e Kimi.",
  ].join("\n");
}

export async function publishExportsToGithub(config: GithubPublishConfig): Promise<GithubPublishResult> {
  const baseRef = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/ref/heads/${encodeURIComponent(config.baseBranch)}`
  );
  const baseCommitSha = baseRef.object.sha as string;

  const baseCommit = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/commits/${baseCommitSha}`
  );
  const baseTreeSha = baseCommit.tree.sha as string;

  const recursiveTree = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/trees/${baseTreeSha}?recursive=1`
  );

  const newPaths = new Set(config.files.map((file) => file.path));
  const existingExportPaths = Array.isArray(recursiveTree.tree)
    ? recursiveTree.tree
        .filter((entry: any) => entry.type === "blob" && typeof entry.path === "string" && entry.path.startsWith("exports/"))
        .map((entry: any) => entry.path as string)
    : [];

  const treeEntries: Array<Record<string, unknown>> = [];
  for (const file of config.files) {
    const blob = await githubRequest<any>(
      config.fetchImpl,
      config.token,
      `https://api.github.com/repos/${config.repo}/git/blobs`,
      {
        method: "POST",
        body: {
          content: file.content,
          encoding: "utf-8",
        },
      }
    );

    treeEntries.push({
      path: file.path,
      mode: "100644",
      type: "blob",
      sha: blob.sha,
    });
  }

  for (const path of existingExportPaths) {
    if (!newPaths.has(path)) {
      treeEntries.push({
        path,
        mode: "100644",
        type: "blob",
        sha: null,
      });
    }
  }

  const tree = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/trees`,
    {
      method: "POST",
      body: {
        base_tree: baseTreeSha,
        tree: treeEntries,
      },
    }
  );

  const commit = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/commits`,
    {
      method: "POST",
      body: {
        message: `chore(sync): publish skills exports for ${config.providers.join(", ")}`,
        tree: tree.sha,
        parents: [baseCommitSha],
      },
    }
  );

  await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/git/refs`,
    {
      method: "POST",
      body: {
        ref: `refs/heads/${config.branchName}`,
        sha: commit.sha,
      },
    }
  );

  const pr = await githubRequest<any>(
    config.fetchImpl,
    config.token,
    `https://api.github.com/repos/${config.repo}/pulls`,
    {
      method: "POST",
      body: {
        title: `chore(sync): publish skills exports`,
        head: config.branchName,
        base: config.baseBranch,
        body: createGithubPrBody(config.manifest, config.providers),
      },
    }
  );

  return {
    branch: config.branchName,
    prUrl: pr.html_url as string,
    filesPublished: config.files.length,
    commitSha: commit.sha as string,
  };
}

export async function uploadFilesToKimi(config: KimiUploadConfig): Promise<KimiUploadResult> {
  const providerFiles = config.files.filter((file) => file.provider === "kimi" && file.path.endsWith(".md"));
  const uploaded: KimiUploadResult["files"] = [];

  for (const file of providerFiles) {
    const formData = new FormData();
    formData.append("purpose", "file-extract");
    formData.append("file", new Blob([file.content], { type: "text/markdown" }), file.path.split("/").pop() || "skill.md");

    const response = await config.fetchImpl("https://api.moonshot.ai/v1/files", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
      },
      body: formData,
    });

    const payload = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(payload?.error?.message || payload?.message || `Kimi upload failed (${response.status})`);
    }

    uploaded.push({
      file_id: payload.id as string,
      filename: payload.filename as string,
      path: file.path,
    });
  }

  return {
    uploaded: uploaded.length,
    files: uploaded,
  };
}

export function prepareSyncFiles(manifest: SkillSyncManifest, providers: SkillSyncProvider[]) {
  return buildSkillSyncFiles(manifest, providers);
}

async function githubRequest<T>(
  fetchImpl: typeof fetch,
  token: string,
  url: string,
  init?: {
    method?: string;
    body?: unknown;
  }
): Promise<T> {
  const response = await fetchImpl(url, {
    method: init?.method || "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: init?.body ? JSON.stringify(init.body) : undefined,
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(payload?.message || `GitHub API request failed (${response.status})`);
  }

  return payload as T;
}
